name: build_and_publish_sphinx_docs

on:
  push:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
    build_and_publish_sphinx:
        runs-on: ubuntu-latest
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        steps:
        - name: Checkout 
          uses: actions/checkout@v4
        - name: Set up Python 3.10
          uses: actions/setup-python@v4
          with:
            python-version: '3.10'
        - name: Install Sphinx, themes, and ghp-import
          run: python -m pip install sphinx sphinx-rtd-theme ghp-import
        - name: Build Docs
          run: |
            cd docs
            make html
            cd ..
        - name: Run ghp-import
          run:
            gph-import -n -p -f docs/_build/html

            
